"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Ao35o73Idon
 */
import { CreateBlog } from "@/app/actions";

import { Button } from "@/components/ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { useRouter } from "next/navigation";
import { FormEvent } from "react";

export function BlogForm() {
  const router = useRouter();

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    console.log("reached here");

    event.preventDefault();
    const formData = new FormData(event.currentTarget);
    const rawData = {
      name: formData.get("name"),
      description: formData.get("description"),
    };
    console.log("data", rawData);
    await CreateBlog(rawData);

    router.push("/ourstory/info");
  }
  return (
    <Card className="w-full max-w-md">
      <CardHeader>
        <CardTitle className="text-center">Create a Blog</CardTitle>
        <CardDescription className="text-center">
          Enter the title and content of your blog.
        </CardDescription>
      </CardHeader>
      <form onSubmit={handleSubmit}>
        <CardContent className="flex flex-col gap-4">
          <div className="flex flex-col gap-1">
            <Label htmlFor="name">Name of the blog</Label>
            <Input
              id="name"
              name="name"
              placeholder="Enter the name of the blog"
              type="text"
            />
          </div>
          <div className="flex flex-col gap-1">
            <Label htmlFor="description">Content Description</Label>
            <Textarea
              className="min-h-[100px]"
              id="description"
              name="description"
              placeholder="Enter the description"
            />
          </div>
        </CardContent>
        <CardFooter className="flex justify-end">
          <Button type="submit">Submit</Button>
        </CardFooter>
      </form>
    </Card>
  );
}
