/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/BB1YOroEF1Q
 */
import { Button } from "./ui/button";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "./ui/card";

export async function BlogCard({ blog }) {
  return (
    <Card className="mx-16 my-4">
      <CardHeader className=" flex items-start gap-4">
        <div className="flex items-center space-x-2">
          <ArrowUpRightIcon className="w-4 h-4" />
          <CardTitle className="text-xs font-semibold leading-none">
            {blog.id}
          </CardTitle>
        </div>
        <div className="ml-auto flex items-center space-x-2">
          <CardTitle className="text-xs font-semibold leading-none">
            {new Date(blog.createdAt).toLocaleDateString()}
          </CardTitle>
          <FileEditIcon className="w-4 h-4" />
        </div>
      </CardHeader>
      <CardContent className="flex flex-col gap-2 text-sm">
        <CardDescription>{blog.description}</CardDescription>
        <CardContent>
          <p className="text-sm">{blog.name}</p>
        </CardContent>
      </CardContent>

      <Button>See more</Button>
    </Card>
  );
}

function ArrowUpRightIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M7 7h10v10" />
      <path d="M7 17 17 7" />
    </svg>
  );
}

function FileEditIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4 13.5V4a2 2 0 0 1 2-2h8.5L20 7.5V20a2 2 0 0 1-2 2h-5.5" />
      <polyline points="14 2 14 8 20 8" />
      <path d="M10.42 12.61a2.1 2.1 0 1 1 2.97 2.97L7.95 21 4 22l.99-3.95 5.43-5.44Z" />
    </svg>
  );
}
