"use client";
/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vZyLopTrCAN
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import axios from "axios";
import { useSession } from "next-auth/react";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { FormEvent } from "react";

export function Landing() {
  const router = useRouter();
  const { data: session, status } = useSession();

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault();
    const data = new FormData(event.currentTarget);

    // @ts-ignore

    try {
      const response = await axios.post("/api/auth/register", {
        email: data.get("email"),
        password: data.get("password"),
        username: data.get("username"),
      });

      if (!response) {
        throw new Error("Network response was not ok");
      }
      console.log("registrations successfull", response);
      router.push("/login");
    } catch (error) {
      console.error("Registration Failed:", error);
    }
  }

  return (
    <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
              Welcome to the Future
            </h1>
            <p className="mx-auto max-w-[600px] text-gray-500 dark:text-gray-400">
              Experience the next generation of innovation. Sign up to stay
              informed.
            </p>
          </div>
          {!session ? (
            <div className="w-full max-w-sm space-y-2">
              {/* @ts-ignore */}
              <form onSubmit={handleSubmit} className="space-y-2">
                <Input
                  placeholder="Enter your name"
                  name="username"
                  required
                  type="text"
                />
                <Input
                  placeholder="Enter your email"
                  name="email"
                  required
                  type="email"
                />
                <Input
                  placeholder="Enter your password"
                  name="password"
                  required
                  type="text"
                />
                <Button type="submit">Sign Up</Button>
              </form>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Sign up to get notified when we launch.
              </p>
            </div>
          ) : (
            <div>
              <h1>Lets get started {session.user.name}</h1>
              <div>
                <h1 className="text-2xl text-black">
                  Create your own story with us
                </h1>
                <Button>
                  <Link href="/ourstory">Create your own story</Link>
                </Button>
              </div>
            </div>
          )}
        </div>
      </div>
    </section>
  );
}
