/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/vZyLopTrCAN
 */
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { getServerSession } from "next-auth";

export async function Landing() {
  const session = await getServerSession();
  return (
    <section className="w-full py-12 md:py-24 lg:py-32 xl:py-48">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center space-y-4 text-center">
          <div className="space-y-2">
            <h1 className="text-3xl font-bold tracking-tighter sm:text-4xl md:text-5xl lg:text-6xl/none">
              Welcome to the Future
            </h1>
            <p className="mx-auto max-w-[600px] text-gray-500 dark:text-gray-400">
              Experience the next generation of innovation. Sign up to stay
              informed.
            </p>
          </div>
          {!session ? (
            <div className="w-full max-w-sm space-y-2">
              <form className="space-y-2">
                <Input placeholder="Name" required type="text" />
                <Input placeholder="Email" required type="email" />
                <Button type="submit">Sign Up</Button>
              </form>
              <p className="text-xs text-gray-500 dark:text-gray-400">
                Sign up to get notified when we launch.
              </p>
            </div>
          ) : (
            <div>Lets get started {session.user.name}</div>
          )}
        </div>
      </div>
    </section>
  );
}
