/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bflb0aNrULh
 */

export function Loading() {
  return (
    <div className="flex flex-col items-center justify-center min-h-screen gap-2 text-center">
      <div />
      <p className="text-sm text-gray-500 dark:text-gray-400">Loading...</p>
    </div>
  );
}
