/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/Xq8DBp9vdR2
 */
import Link from "next/link";

export function Navbar() {
  return (
    <nav className="flex h-16 w-full items-center px-4 md:px-6 border-t-2 border-gray-200 border-gray-200/90 dark:border-gray-800/90">
      <div className="w-12 mr-4 flex items-center shrink-0">
        <Link
          className="flex items-center w-10 h-10 rounded-full border border-gray-200 border-gray-800/50 dark:border-gray-950 dark:border-gray-950"
          href="/"
        >
          <MountainIcon className="h-6 w-6 text-gray-500 dark:text-gray-400" />
          <span className="sr-only">Acme Inc</span>
        </Link>
      </div>
      <nav className="flex flex-1 justify-end gap-4">
        <Link
          className="inline-flex h-9 items-center rounded-md px-2.5 text-sm font-medium underline underline-entire transition-colors hover:text-gray-900 dark:hover:text-gray-50"
          href="/"
        >
          Home
        </Link>
        <Link
          className="inline-flex h-9 items-center rounded-md px-2.5 text-sm font-medium underline underline-entire transition-colors hover:text-gray-900 dark:hover:text-gray-50"
          href="/membership"
        >
          Membership
        </Link>
        <Link
          className="inline-flex h-9 items-center rounded-md px-2.5 text-sm font-medium underline underline-entire transition-colors hover:text-gray-900 dark:hover:text-gray-50"
          href="/ourstory"
        >
          Our-story
        </Link>
        <Link
          className="inline-flex h-9 items-center rounded-md px-2.5 text-sm font-medium underline underline-entire transition-colors hover:text-gray-900 dark:hover:text-gray-50"
          href="/login"
        >
          Signin
        </Link>
        <Link
          className="inline-flex h-9 items-center rounded-md px-2.5 text-sm font-medium underline underline-entire transition-colors hover:text-gray-900 dark:hover:text-gray-50"
          href="/register"
        >
          Get-Started
        </Link>
      </nav>
    </nav>
  );
}

function MountainIcon(props: any) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>
  );
}
