/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/NZyFuEVNQKv
 */
import {
  Card,
  CardDescription,
  CardFooter,
  CardHeader,
  CardTitle,
} from "./ui/card";

export function Userblogcard({ blog }) {
  return (
    <Card>
      <CardHeader>
        <CardTitle>{blog.id}</CardTitle>
        <CardDescription>{blog.description}</CardDescription>
      </CardHeader>
      <CardFooter>
        <div className="text-sm font-medium grid gap-1.5">
          <p>Created by: {blog.createdBy}</p>
          <p>Created at: 2023-08-29</p>
        </div>
      </CardFooter>
    </Card>
  );
}
